export const Secretariat = [
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476439/events/nitsmun/team/marufPadaya_faj39h.jpg",
    alt: "Maruf Padaya",
    name: "Maruf Padaya",
    post: "Sacretary General",
    linkedin: "https://www.linkedin.com/in/maruf-padaya-a865151bb",
    fb: "https://www.facebook.com/maruf.padaya",
    mail: "mailto:marufpadaya786@gmail.com",
  },
  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476257/events/nitsmun/team/eishaHalder_dkjwgf.jpg",
    alt: "Eisha Halder",
    name: "Eisha Halder",
    post: "Director General",
    linkedin: "https://www.linkedin.com/in/eisha-halder-a42367200",
    fb: "https://www.facebook.com/eisha.halder.16",
    mail: "mailto:eisha20_ug@cse.nits.ac.in",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476735/events/nitsmun/team/pranjalKumarSingh_adqmoi.jpg",
    alt: "Pranjal Kumar Singh",
    name: "Pranjal Kumar Singh",
    post: "Director General",
    linkedin: "https://www.linkedin.com/in/pranjal-singh-b17037201",
    fb: "https://www.facebook.com/profile.php?id=100005172197980",
    mail: "mailto:pranjal7802@gmail.com",
  },
  {
    id: 4,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476192/events/nitsmun/team/dhirazitHazarika_pzucs3.png",
    alt: "Dhirazit Hazarika",
    name: "Dhirazit Hazarika",
    post: "General Secretary",
    linkedin: "https://www.linkedin.com/",
    fb: "https://www.facebook.com/dhirazit.hazarika",
    mail: "mailto:dhirazit20_ug@mech.nits.ac.in",
  },
  {
    id: 5,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476898/events/nitsmun/team/reetomRanaDutta_jjb837.jpg",
    alt: "Reetom Rana Dutta",
    name: "Reetom Rana Dutta",
    post: "Director Media & Design",
    linkedin: "https://www.linkedin.com/in/reetom-rana-dutta-34156220a",
    fb: "https://www.facebook.com/reetom.ranadutta",
    mail: "mailto:reetom20_ug@ee.nits.ac.in",
  },
  {
    id: 6,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477495/events/nitsmun/team/tanmayTripathy_t73soe.jpg",
    alt: "Tanmay Tripathy",
    name: "Tanmay Tripathy",
    post: "Director Media & Design",
    linkedin: "https://www.linkedin.com/in/tanmay-tripathy/",
    fb: "https://www.facebook.com/profile.php?id=100009726932773",
    mail: "mailto:ttripathy17@gmail.com",
  },
  {
    id: 7,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476048/events/nitsmun/team/bishalKarmakar_pywxdf.jpg",
    alt: "Bishal Karmakar",
    name: "Bishal Karmakar",
    post: "Director Public Relations & Outreach",
    linkedin: "https://www.linkedin.com/in/bishal-karmakar-26942a20b/",
    fb: "https://www.facebook.com/profile.php?id=100011434842985",
    mail: "mailto:bishalkarmakar123456@gmail.com",
  },
  {
    id: 8,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477390/events/nitsmun/team/somadritaHalder_mz5jbp.jpg",
    alt: "Somadrita Halder",
    name: "Somadrita Halder",
    post: "Director Public Relations & Outreach",
    linkedin: "https://www.linkedin.com/mwlite/in/somadrita-halder-46156220a",
    fb: "https://m.facebook.com/somadrita.halder?ref=bookmarks",
    mail: "mailto:somadrita20_ug@mech.nits.ac.in",
  },
  {
    id: 9,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477253/events/nitsmun/team/sauravSuman_hpn56k.jpg",
    alt: "Saurav Suman",
    name: "Saurav Suman",
    post: "Director Liaison & Delegate Affairs",
    linkedin: "https://www.linkedin.com/in/saurav-suman-49a78620a",
    fb: "https://www.facebook.com/saurav.suman.7946281",
    mail: "mailto:sumanism1102@gmail.com",
  },
  {
    id: 10,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477220/events/nitsmun/team/sauravPal_luh8rf.jpg",
    alt: "Saurav Pal",
    name: "Saurav Pal",
    post: "Director Technical Operations",
    linkedin: "https://www.linkedin.com/in/resyfer/",
    fb: "https://github.com/resyfer",
    mail: "mailto:palsaurav.2020@gmail.com",
  },
  {
    id: 11,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476015/events/nitsmun/team/bijuBorah_fyjn1q.jpg",
    alt: "Biju Borah",
    name: "Biju Borah",
    post: "Director Technical Operations",
    fb: "https://github.com/biju-borah",
    linkedin: "https://www.linkedin.com/in/biju-borah-1bb78620a",
    mail: "mailto:biju20_ug@ee.nits.ac.in",
  },
  {
    id: 12,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476156/events/nitsmun/team/devendarSainadhGorla_cqauua.jpg",
    alt: "Devendar Sainadh Gorla",
    name: "Devendar Sainadh Gorla",
    post: "Director Logistics",
    linkedin: "https://www.linkedin.com/in/devendar-sainadh-gorla-9021a91b5",
    fb: "https://www.facebook.com/devendar1729",
    mail: "mailto:devendargorla@gmail.com",
  },
];
export const Secretariatjr = [
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475732/events/nitsmun/aditi_MUN_o2zaxx.jpg",
    alt: "Aditi Archita Khataniar",
    name: "Aditi Archita Khataniar",
    post: "Deputy Director General",
    linkedin: "https://in.linkedin.com/in/aditi-archita-khataniar-2189a3226",
    fb: "https://www.facebook.com/mumpyyyyyyy",
    mail: "mailto:aditi.khataniar@gmail.com",
  },
  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477071/events/nitsmun/team/Ronak_Jain_etgqal.jpg",
    alt: "Ronak Jain",
    name: "Ronak Jain",
    post: "Deputy Director General",
    linkedin: "https://www.linkedin.com/in/ronak4195/",
    fb: "https://www.facebook.com/ronak4195",
    mail: "mailto:4195rj@gmail.com",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476938/events/nitsmun/team/rishavnegi_n2aajx.jpg",
    alt: "Rishav Singh Negi",
    name: "Rishav Singh Negi",
    post: "Deputy Director Media & Design",
    linkedin: "https://www.linkedin.com/in/rishav-negi-03a62b17a",
    fb: "https://www.facebook.com/profile.php?id=100087438950717&mibextid=ZbWKwL",
    mail: "mailto:rishavnegi007@gmail.com",
  },
  {
    id: 4,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475904/events/nitsmun/team/Amrita_kashyap_nmvsdf.jpg",
    alt: "Amrita Kashyap",
    name: "Amrita Kashyap",
    post: "Deputy Director Media & Design",
    linkedin: "https://www.linkedin.com/in/amrita-kashyap-a33069230",
    fb: "https://www.facebook.com/profile.php?id=100076495782914",
    mail: "mailto:amrita7734kashyap@gmail.com",
  },
  {
    id: 5,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476862/events/nitsmun/team/ranjanKapar_j4hqgc.jpg",
    alt: "Ranjan Kr Kapar",
    name: "Ranjan Kr Kapar",
    post: "Deputy Director Media & Design",
    linkedin: "https://www.linkedin.com/in/ranjan-kr-kapar-643157229",
    fb: "https://www.facebook.com/ranjan.kapar.9",
    mail: "mailto:ranjan21_ug@mech.nits.ac.in",
  },
  {
    id: 6,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475868/events/nitsmun/team/akshita_hazarika_fqnwky.jpg",
    alt: "Akshita Hazarika",
    name: "Akshita Hazarika",
    post: "Deputy Director Media & Design",
    linkedin: "https://www.linkedin.com/in/akshita-hazarika-ab7512226",
    fb: "https://www.facebook.com/profile.php?id=100074174147812",
    mail: "mailto:akshita.hazarika1702@gmail.com",
  },
  {
    id: 7,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476080/events/nitsmun/team/Chayan_tya1ek.jpg",
    alt: "Chayan Gulgulia",
    name: "Chayan Gulgulia",
    post: "Deputy Director Public Relations & Outreach",
    mail: "mailto:chayanjn24@gmail.com",
    linkedin: "https://www.linkedin.com/in/chayan-gulgulia/",
    fb: "https://www.facebook.com/karya.jain.3",
  },
  {
    id: 8,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477032/events/nitsmun/team/rohit1_eh4kdf.png",
    alt: "Rohit Choudhary",
    name: "Rohit Choudhary",
    post: "Deputy Director Public Relations & Outreach",
    mail: "mailto:postmail.rohit@gmail.com",
    linkedin: "www.linkedin.com/in/rohit-choudhary-74501522a",
    fb: "https://www.facebook.com/profile.php?id=100076216899401",
  },
  {
    id: 9,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476399/events/nitsmun/team/khush_MUN_w0cszx.jpg",
    alt: "Khush Agarwal",
    name: "Khush Agarwal",
    post: "Deputy Director Public Relations & Outreach",
    mail: "mailto:khush.aggarwal28@gmail.com",
    linkedin: "https://www.linkedin.com/in/khush-aggarwal-ab9837227",
    fb: "https://www.facebook.com/khush.aggarwal.7?mibextid=ZbWKwL",
  },
  {
    id: 10,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477322/events/nitsmun/team/sayantanDas_xiusrh.jpg",
    alt: "Sayantan Das",
    name: "Sayantan Das",
    post: "Deputy Director Public Relations & Outreach",
    mail: "mailto:sayantan21_ug@ei.nits.ac.in",
    linkedin: "https://www.linkedin.com/in/sayantan-das-0310951ba",
    fb: "https://www.facebook.com/sayantan.das.12764874",
  },
  {
    id: 11,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475981/events/nitsmun/team/Bhargabi_Nath_yepwww.jpg",
    alt: "Bhargabi Nath",
    name: "Bhargabi Nath",
    post: "Deputy Director Liaison & Delegate Affairs",
    linkedin: "https://www.linkedin.com/in/bhargavi-nath-9a8a81223",
    fb: "https://www.facebook.com/bhargavi.nath",
    mail: "mailto:bhargavinath.24@gmail.com",
  },
  {
    id: 12,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477462/events/nitsmun/team/Suraj_Kumar_Pampana_e3kaio.jpg",
    alt: "Suraj Kumar Pampana",
    name: "Suraj Kumar Pampana",
    post: "Deputy Director Liaison & Delegate Affairs",
    linkedin: "https://www.linkedin.com/in/surajkumart1542960s",
    fb: "https://www.facebook.com/Suraj28.11.03",
    mail: "mailto:suraj.pampana@gmail.com",
  },
  {
    id: 13,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676477584/events/nitsmun/team/Ankit3_stpz8d.jpg",
    alt: "Ankit Upadhaya",
    name: "Ankit Upadhaya",
    post: "Deputy Director Technical Operations",
    mail: "mailto:ankitupadhaya07@gmail.com",
    linkedin: "https://www.linkedin.com/in/ankit-upadhaya07",
    fb: "https://github.com/ankit07an",
  },
  {
    id: 14,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/v1681359339/perosnal/edited_aditya_ranjan_lyx5ns.webp",
    alt: "Aditya Ranjan",
    name: "Aditya Ranjan",
    post: "Deputy Director Technical Operations",
    mail: "mailto:hereisadi@pm.me",
    linkedin: "https://www.linkedin.com/in/aditya-ranjan-77a6a522b/",
    fb: "https://github.com/hereisadi",
  },
  {
    id: 15,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476226/events/nitsmun/team/dorothy2_zk4myd.jpg",
    alt: "Dorothy Phukon",
    name: "Dorothy Phukon",
    post: "Deputy Director Technical Operations",
    mail: "mailto:dorothy21_ug@ee.nits.ac.in",
    linkedin: "https://www.linkedin.com/in/dorothy-phukon-48a066230",
    fb: "https://github.com/dorothyp12",
  },
];
// export const Secretariatmediajr = [
//   // {
//   //   id: 1,
//   //   cName: "team-sec",
//   //   imgsrc: "./Images/Rimlee Ghosh.jpg",
//   //   alt: "Rimlee Ghosh",
//   //   name: "Rimlee Ghosh",
//   //   post: "Media & Design Team",
//   //   linkedin: "https://www.linkedin.com/in/rimlee-ghosh-678b65237",
//   //   fb: "https://www.facebook.com/profile.php?id=100075884483252",
//   //   mail: "mailto:rimlee21_ug@ee.nits.ac.in",
//   // },
// {
//   id: 1,
//   cName: "team-sec",
//   imgsrc: "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475868/events/nitsmun/team/akshita_hazarika_fqnwky.jpg",
//   alt: "Akshita Hazarika",
//   name: "Akshita Hazarika",
//   post: "Media & Design Team",
//   linkedin: "https://www.linkedin.com/in/akshita-hazarika-ab7512226",
//   fb: "https://www.facebook.com/profile.php?id=100074174147812",
//   mail: "mailto:akshita.hazarika1702@gmail.com",
// },

// {
//   id: 2,
//   cName: "team-sec",
//   imgsrc: "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476862/events/nitsmun/team/ranjanKapar_j4hqgc.jpg",
//   alt: "Ranjan Kr Kapar",
//   name: "Ranjan Kr Kapar",
//   post: "Media & Design Team",
//   linkedin: "https://www.linkedin.com/in/ranjan-kr-kapar-643157229",
//   fb: "https://www.facebook.com/ranjan.kapar.9",
//   mail: "mailto:ranjan21_ug@mech.nits.ac.in",
// },
// {
//   id: 3,
//   cName: "team-sec",
//   imgsrc: "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676475904/events/nitsmun/team/Amrita_kashyap_nmvsdf.jpg",
//   alt: "Amrita Kashyap",
//   name: "Amrita Kashyap",
//   post: "Media & Design Team",
//   linkedin: "https://www.linkedin.com/in/amrita-kashyap-a33069230",
//   fb: "https://www.facebook.com/profile.php?id=100076495782914",
//   mail: "mailto:amrita7734kashyap@gmail.com",
// },
// {
//   id: 4,
//   cName: "team-sec",
//   imgsrc: "https://res.cloudinary.com/dp92qug2f/image/upload/c_scale,w_360,f_auto,fl_lossy/v1676476938/events/nitsmun/team/rishavnegi_n2aajx.jpg",
//   alt: "Rishav Singh Negi",
//   name: "Rishav Singh Negi",
//   post: "Media & Design Team",
//   linkedin: "https://www.linkedin.com/in/rishav-negi-03a62b17a",
//   fb: "https://www.facebook.com/profile.php?id=100087438950717&mibextid=ZbWKwL",
//   mail: "mailto:rishavnegi007@gmail.com",
// },
// ];

export const Secretariatmediajr = [
  // {
  //   id: 1,
  //   cName: "team-sec",
  //   imgsrc: "./Images/Rimlee Ghosh.jpg",
  //   alt: "Rimlee Ghosh",
  //   name: "Rimlee Ghosh",
  //   post: "Media & Design Team",
  //   linkedin: "https://www.linkedin.com/in/rimlee-ghosh-678b65237",
  //   fb: "https://www.facebook.com/profile.php?id=100075884483252",
  //   mail: "mailto:rimlee21_ug@ee.nits.ac.in",
  // },
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931106/nitsmun/ayush_sdvmfc.webp",
    alt: "Aayush Sharma ",
    name: "Aayush Sharma ",
    post: "Media & Design Team",
    linkedin: "http://www.linkedin.com/in/aayush1304",
    fb: "https://www.facebook.com/Aayush.Sharma.fb/",
    mail: "mailto:aayushsharma1304@gmail.com",
  },

  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931105/nitsmun/gracie_dsp5vs.webp",
    alt: "Gracie G Rabha",
    name: "Gracie G Rabha",
    post: "Media & Design Team",
    linkedin: "https://www.linkedin.com/in/gracie-g-rabha-4472621aa",
    fb: "https://www.facebook.com/profile.php?id=100087872117590&mibextid=ZbWKwL",
    mail: "mailto:gracieruth2505@gmail.com",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931103/nitsmun/kaustabh_kiwlfm.webp",
    alt: "Kaustav Dev",
    name: "Kaustav Dev",
    post: "Media & Design Team",
    linkedin: "https://www.linkedin.com/in/kaustav-dev-429123248",
    fb: "https://www.facebook.com/profile.php?id=100087939076312&mibextid=ZbWKwL",
    mail: "mailto:devkaustav769@gmail.com",
  },
  {
    id: 4,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931107/nitsmun/dhritimaan_ch4o4q.webp",
    alt: "Dhritimaan Hazarika",
    name: "Dhritimaan Hazarika",
    post: "Media & Design Team",
    linkedin: "https://www.linkedin.com/in/dhritimaan-hazarika-5131a0259",
    fb: "https://www.facebook.com/profile.php?id=100087984024219",
    mail: "mailto:dhritimaan02@gmail.com",
  },
];

export const Secretariatresearchjr = [
  // {
  //   id: 1,
  //   cName: "team-sec",
  //   imgsrc: "./Images/vishesh1.jpg",
  //   alt: "Vishesh",
  //   name: "Vishesh",
  //   post: "Research and Development Team",
  //   mail: "mailto:vishesh21_ug@cse.nits.ac.in",
  //   linkedin: "https://www.linkedin.com/in/vishesh-vishesh-1860a4229/",
  //   fb: "https://www.facebook.com/profile.php?id=100075987946323",
  // },
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931106/nitsmun/bhaswar_dx9d8o.webp",
    alt: "Bhaswar Agnivesh",
    name: "Bhaswar Agnivesh",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/bhaswar-agnivesh-b90825293?trk=contact-info",
    fb: "https://www.facebook.com/profile.php?id=100087858823510&mibextid=ZbWKwL",
    mail: "mailto:bhaswaragnivesh@gmail.com",
  },
  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931103/nitsmun/paditya_kogiwt.webp",
    alt: "Pidaparthi Satyasai Aditya",
    name: "Pidaparthi Satyasai Aditya",
    post: "Research and Development Team",
    linkedin: "http://linkedin.com/in/p-sathya-sai-aditya-022b58253",
    fb: "https://www.facebook.com/profile.php?id=100087007144018",
    mail: "mailto:psathyasaiaditya@gmail.com",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931105/nitsmun/dewang_nk4ilm.webp",
    alt: "Dewang Bawri",
    name: "Dewang Bawri",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/dewang-bawri-37885724a",
    fb: "https://m.facebook.com/profile.php/?id=100014583841018&name=STSDirectNavUserDecorator",
    mail: "mailto:bawridewang210@gmail.com",
  },
  {
    id: 4,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/barbi_alsh1h.webp",
    alt: "Barbi Chaliha",
    name: "Barbi Chaliha",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/barbi-chaliha-395972254",
    fb: "https://www.facebook.com/profile.php?id=100087897555374",
    mail: "mailto:barbic_ug_22@ece.nits.ac.in",
  },
  {
    id: 5,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931103/nitsmun/p_harsh_geatf1.webp",
    alt: "P Shri Harsh",
    name: "P Shri Harsh",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/pragada-phani-shri-harsh-5b6469258",
    fb: "https://www.facebook.com/profile.php?id=100088211767635&mibextid=ZbWKwL",
    mail: "mailto:shriharsh0407@gmail.com",
  },
  {
    id: 6,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931105/nitsmun/vishnu_priya_m7rmcz.webp",
    alt: "Vishnu Priya",
    name: "Vishnu Priya",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/vishnu-priya-243418247",
    fb: "https://www.facebook.com/profile.php?id=100082966149038&mibextid=ZbWKwL",
    mail: "mailto:vishnupriyavivek13@gmail.com",
  },
  {
    id: 7,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dp92qug2f/image/upload/v1698840691/poorna_iddn6u.webp",
    alt: "POORNA MANI SANKAR PAKKI",
    name: "Poorna Mani Sankar Pakki",
    post: "Research and Development Team",
    linkedin: "https://www.linkedin.com/in/poorna-mani-sankar-584515257/",
    fb: "https://www.facebook.com/profile.php?id=100083663637015",
    mail: "mailto:poornamanisankar@gmail.com",
  },
];
export const Secretariatprjr = [
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931102/nitsmun/mayurakhi_a8xhjj.webp",
    alt: "Mayurakhi Khaund",
    name: "Mayurakhi Khaund",
    post: "Public Relations & Outreach Team",
    mail: "mailto:mayurakhikhaund7@gmail.com",
    linkedin: "https://www.linkedin.com/in/mayurakhi-khaund-039981257",
    fb: "https://www.facebook.com/profile.php?id=100087804338539&mibextid=ZbWKwL",
  },
  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/arihant_r5m73m.webp",
    alt: "Arihant Tiwari",
    name: "Arihant Tiwari",
    post: "Public Relations & Outreach Team",
    mail: "mailto:arihanttiwari1@gmail.com",
    linkedin: "https://www.linkedin.com/in/arihant-tiwari-558b39257",
    fb: "https://www.facebook.com/profile.php?id=100088291966046&mibextid=ZbWKwL",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/debaditya_exshot.webp",
    alt: "Debaditya Bhattacharjee",
    name: "Debaditya Bhattacharjee",
    post: "Public Relations & Outreach Team",
    mail: "mailto:bhattacharjeedebaditya1234@gmail.com",
    linkedin: "https://www.linkedin.com/in/debaditya-bhattacharjee-ab57a5244",
    fb: "https://www.facebook.com/profile.php?id=100088157643554",
  },
  {
    id: 4,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/bishal_paul_biswas_fhcjso.webp",
    alt: "Bishal Paul Biswas",
    name: "Bishal Paul Biswas",
    post: "Public Relations & Outreach Team",
    mail: "mailto:bishalp.biswas@gmail.com",
    linkedin: "https://www.linkedin.com/in/bishal-paul-biswas-592341257/",
    fb: "https://www.facebook.com/profile.php?id=100087658158317",
  },
  {
    id: 5,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/tripti_ydvxdv.webp",
    alt: "Tripti Golchha",
    name: "Tripti Golchha",
    post: "Public Relations & Outreach Team",
    mail: "mailto:triptigold02@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/tripti-golchha-b7066818b?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BY7ZnB0uUQoG8vO8uq7FbgA%3D%3D",
    fb: "https://www.facebook.com/tripti.golchha.1/",
  },
  {
    id: 6,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931102/nitsmun/alya_jain_yazhvn.webp",
    alt: "Aalya Jain",
    name: "Aalya Jain",
    post: "Public Relations & Outreach Team",
    mail: "mailto:Aalyaj_ug_22@ee.nits.ac.in",
    linkedin: "https://www.linkedin.com/in/aalya-jain-ab1658262",
    fb: "https://www.facebook.com/profile.php?id=100087870020285&mibextid=ZbWKwL",
  },
];
export const Secretariatwebjr = [
  {
    id: 1,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dxdxzcn0q/image/upload/v1694600896/ECS%20Website/barnil_or2isx.jpg",
    alt: "Barnil Sarma",
    name: "Barnil Sarma",
    post: "Technical Team",
    mail: "mailto:barnilsarma@gmail.com",
    linkedin: "https://www.linkedin.com/in/barnil-sarma-34383a255?trk=contact-info",
    fb: "https://github.com/barnilsarma",
  },
  {
    id: 2,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1695931104/nitsmun/samarjit_yzad4o.webp",
    alt: "Samarjit Roy",
    name: "Samarjit Roy",
    post: "Technical Team",
    mail: "mailto:samarjitroy025@gmail.com",
    linkedin: "https://www.linkedin.com/in/samarjit-roy-368071257/",
    fb: "https://github.com/Samarjit25",
  },
  {
    id: 3,
    cName: "team-sec",
    imgsrc:
      "https://res.cloudinary.com/dhry5xscm/image/upload/v1700683185/nitsmun/bitopan-img_h61um4.webp",
    alt: "Bitopan Baishya",
    name: "Bitopan Baishya",
    post: "Technical Team",
    mail: "mailto:bitopanbaishya2@gmail.com",
    linkedin: "https://www.linkedin.com/in/bitopanbaishya",
    fb: "https://github.com/BitopanBaishya",
  },
];
